# Generated by Django 2.2.9 on 2020-01-17 16:01

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='Post Date')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('body', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='title')),
                                                          ('paragraph', wagtail.core.blocks.RichTextBlock()),
                                                          ('image', wagtail.images.blocks.ImageChooserBlock()),
                                                          ('quote', wagtail.core.blocks.BlockQuoteBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
