# Generated by Django 2.2.9 on 2020-02-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=5, unique=True, verbose_name='Registration')),
                ('type', models.CharField(max_length=255, verbose_name='Aircraft Type')),
                ('is_club_aircraft', models.BooleanField(verbose_name='Our Aircraft?')),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Flight Date')),
                ('capacity',
                 models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('EX', 'Examiner'), ('INS', 'Instructor')],
                                  default='P2', max_length=32, verbose_name='Pilot Capacity')),
                ('duration', models.IntegerField(verbose_name='Flight Duration')),
                ('is_launch_failure', models.BooleanField(default=False, verbose_name='Is Launch Fail?')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugc.Aircraft')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
