# Generated by Django 2.2.9 on 2020-02-26 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sugc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glidingfeeperiod',
            name='junior_subs_mins',
            field=models.IntegerField(default=15, verbose_name="Juniors' Subsidised Amount of Minutes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glidingfeeperiod',
            name='std_subs_mins',
            field=models.IntegerField(default=15, verbose_name='Standard Subsidised Amount of Minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glidingfeeperiod',
            name='std_age',
            field=models.IntegerField(verbose_name='Age from which to charge standard fees'),
        ),
        migrations.CreateModel(
            name='FlyingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Flying List Date')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='flyinglists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
