# Generated by Django 2.2.9 on 2020-05-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='flights', to='sugc.FeesInvoice'),
        ),
    ]
