# Generated by Django 2.2.9 on 2020-02-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(verbose_name='Flight Duration [mins]'),
        ),
    ]
