# Generated by Django 2.2.9 on 2020-02-23 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('sugc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feesinvoice',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
