# Generated by Django 2.2.9 on 2020-02-20 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sugc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
