# Generated by Django 2.2.9 on 2020-06-20 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('sugc', '0003_auto_20200619_1528'), ('sugc', '0004_auto_20200619_1652'),
                ('sugc', '0005_auto_20200619_1748'), ('sugc', '0006_auto_20200619_1808'),
                ('sugc', '0007_auto_20200620_1054'), ('sugc', '0008_remove_flight_invoiced_for')]

    dependencies = [
        ('sugc', '0002_auto_20200503_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='glidingfeeperiod',
            name='name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Fee Model Name'),
        ),
        migrations.CreateModel(
            name='GlidingFeeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Fee Group Name')),
                ('applicability_condition', models.CharField(max_length=300, verbose_name='Applicability Condition')),
                ('launch_cost', models.FloatField(verbose_name='Actual Launch Cost')),
                ('tlf_cost', models.FloatField(verbose_name='Actual TLF Cost')),
                ('minute_cost', models.FloatField(verbose_name='Actual Minute Cost')),
                ('subs_mins', models.IntegerField(verbose_name='Subsidised Amount of Minutes')),
                ('subs_launch_cost', models.FloatField(verbose_name='Subsidised Launch Cost')),
                ('subs_tlf_cost', models.FloatField(verbose_name='Subsidised TLF Cost')),
                ('subs_minute_cost', models.FloatField(verbose_name='Subsidised Minute Cost')),
            ],
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='junior_launch_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='junior_minute_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='junior_subs_launch_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='junior_subs_mins',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='junior_subs_minute_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='junior_subs_tlf_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='junior_tlf_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='std_age',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='std_launch_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='std_minute_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='std_subs_launch_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='std_subs_mins',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='std_subs_minute_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='std_subs_tlf_cost',
        ),
        migrations.RemoveField(
            model_name='glidingfeeperiod',
            name='std_tlf_cost',
        ),
        migrations.AddField(
            model_name='glidingfeeperiod',
            name='fee_groups',
            field=models.ManyToManyField(to='sugc.GlidingFeeGroup'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='custom_fee_groups',
            field=models.ManyToManyField(blank=True, to='sugc.GlidingFeeGroup'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feesinvoice',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sugc.Aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='flights', to='sugc.FeesInvoice'),
        ),
        migrations.AlterField(
            model_name='flyinglist',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='flight',
            name='invoiced_for',
        ),
    ]
