# Generated by Django 2.2.9 on 2020-02-22 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sugc', '0002_auto_20200221_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(verbose_name='Flying Date')),
                ('invoice_balance', models.FloatField(default=0.0, verbose_name='Flying Fees Due')),
                ('invoice_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('invoiced_member',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
