# Generated by Django 2.2.9 on 2020-07-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0003_auto_20200619_1528_squashed_0008_remove_flight_invoiced_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='glidingfeegroup',
            name='daily_cost',
            field=models.FloatField(default=0, verbose_name='Daily Rental Cost'),
            preserve_default=False,
        ),
    ]
