# Generated by Django 2.2.9 on 2020-02-22 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0003_feesinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesinvoice',
            old_name='invoice_balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='feesinvoice',
            old_name='invoice_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='feesinvoice',
            old_name='invoiced_member',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='feesinvoice',
            old_name='invoice_paid',
            new_name='paid',
        ),
    ]
