# Generated by Django 2.2.9 on 2020-02-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0003_auto_20200220_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlidingFeePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_effective_from', models.DateField(verbose_name='Date Fees effective from')),
                ('junior_launch_cost', models.FloatField(verbose_name="Juniors' Actual Launch Cost")),
                ('junior_tlf_cost', models.FloatField(verbose_name="Juniors' Actual TLF Cost")),
                ('junior_minute_cost', models.FloatField(verbose_name="Juniors' Actual Minute Cost")),
                ('junior_subs_launch_cost', models.FloatField(verbose_name="Juniors' Subsidised Launch Cost")),
                ('junior_subs_tlf_cost', models.FloatField(verbose_name="Juniors' Subsidised TLF Cost")),
                ('junior_subs_minute_cost', models.FloatField(verbose_name="Juniors' Subsidised Minute Cost")),
                ('std_launch_cost', models.FloatField(verbose_name='Standard Actual Launch Cost')),
                ('std_tlf_cost', models.FloatField(verbose_name='Standard Actual TLF Cost')),
                ('std_minute_cost', models.FloatField(verbose_name='Standard Actual Minute Cost')),
                ('std_subs_launch_cost', models.FloatField(verbose_name='Standard Subsidised Launch Cost')),
                ('std_subs_tlf_cost', models.FloatField(verbose_name='Standard Subsidised TLF Cost')),
                ('std_subs_minute_cost', models.FloatField(verbose_name='Standard Subsidised Minute Cost')),
                ('std_age', models.IntegerField(verbose_name='Age at which to charge standard fees')),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='is_launch_failure',
        ),
        migrations.AddField(
            model_name='flight',
            name='is_real_launch_failure',
            field=models.BooleanField(default=False, verbose_name='RLF?'),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_train_launch_failure',
            field=models.BooleanField(default=False, verbose_name='TLF?'),
        ),
    ]
