# Generated by Django 2.2.9 on 2020-02-21 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0004_auto_20200221_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glidingfeeperiod',
            options={'ordering': ['-date_effective_from']},
        ),
    ]
