# Generated by Django 2.2.9 on 2020-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0004_auto_20200222_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='invoiced_for',
            field=models.BooleanField(default=False, editable=False, verbose_name='Invoiced For'),
        ),
    ]
