# Generated by Django 2.2.9 on 2020-07-30 00:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0005_auto_20200710_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='flyinglist',
            options={'ordering': ['-date']},
        ),
    ]
