# Generated by Django 3.2.6 on 2021-08-03 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0006_auto_20200730_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date_available'], 'verbose_name': 'Available Day',
                     'verbose_name_plural': 'Availability'},
        ),
    ]
