# Generated by Django 3.2.6 on 2023-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '0007_alter_availability_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='import_hash',
            field=models.IntegerField(blank=True, null=True, verbose_name='Import Hash'),
        ),
    ]
