# Generated by Django 3.2.6 on 2021-08-03 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_auto_20200117_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['domain'], 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
