# Generated by Django 2.2.9 on 2020-06-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_alumni',
            field=models.BooleanField(default=False, verbose_name='Alumni?'),
        ),
    ]
