# Generated by Django 2.2.9 on 2020-01-17 16:01

from django.db import migrations, models

import sugc.users.validators


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('date_available',
                 models.DateField(validators=[sugc.users.validators.not_in_past_validator], verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Available Day',
                'verbose_name_plural': 'Availability',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_bronze',
            field=models.BooleanField(default=False, verbose_name='Bronze?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_solo',
            field=models.BooleanField(default=False, verbose_name='Solo?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_xc',
            field=models.BooleanField(default=False, verbose_name='XC?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.ManyToManyField(to='users.Availability'),
        ),
    ]
