# Generated by Django 2.2.9 on 2020-01-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20200117_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_bronze',
            field=models.BooleanField(default=False, verbose_name='Bronze?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_solo',
            field=models.BooleanField(default=False, verbose_name='Solo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_xc',
            field=models.BooleanField(default=False, verbose_name='XC?'),
        ),
    ]
