# Generated by Django 2.2.9 on 2020-01-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20200117_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.FileField(default=None, upload_to='user_media'),
            preserve_default=False,
        ),
    ]
