# Generated by Django 2.2.9 on 2020-07-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_user_is_third_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='Phone Number'),
        ),
    ]
