# Generated by Django 2.2.9 on 2020-01-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='user_media'),
        ),
    ]
