# Generated by Django 2.2.9 on 2020-01-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_auto_20200117_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.FileField(default='images/profile_default', upload_to='user_media'),
        ),
    ]
