# Generated by Django 3.2.7 on 2021-09-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, verbose_name='Has completed the onboarding forms?'),
        ),
    ]
