# Generated by Django 2.2.9 on 2020-01-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20200117_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.FileField(default='images/profile_default.jpg', upload_to='user_media'),
        ),
    ]
