# Generated by Django 2.2.9 on 2020-01-19 13:22

from django.db import migrations, models

import sugc.users.validators


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_auto_20200118_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date_available',
            field=models.DateField(unique=True, validators=[sugc.users.validators.not_in_past_validator],
                                   verbose_name='Available'),
        ),
    ]
