# Generated by Django 2.2.9 on 2020-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sugc', '__first__'),
        ('users', '0008_auto_20200119_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flights',
            field=models.ManyToManyField(related_name='flights', to='sugc.Flight'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='images/profile_default.jpg', upload_to='user_media/'),
        ),
    ]
