# Generated by Django 2.2.9 on 2020-02-20 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_auto_20200220_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='flights',
        ),
    ]
