# Generated by Django 2.2.9 on 2020-02-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_remove_user_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_susu_membership',
            field=models.BooleanField(default=False, verbose_name='Has SUSU Membership?'),
        ),
        migrations.AddField(
            model_name='user',
            name='waiting_list_position',
            field=models.IntegerField(default=0, verbose_name='Waiting List Position'),
        ),
    ]
