# Generated by Django 2.2.9 on 2020-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_auto_20200220_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='waiting_list_position',
        ),
        migrations.AddField(
            model_name='user',
            name='on_waiting_list',
            field=models.BooleanField(default=True, verbose_name='On Waiting List?'),
        ),
    ]
