# Generated by Django 2.2.9 on 2020-02-21 21:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_auto_20200221_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Account Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 2, 21), verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
