# Generated by Django 2.2.9 on 2020-02-21 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0014_auto_20200221_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
