# Generated by Django 2.2.9 on 2020-02-21 23:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_auto_20200221_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
    ]
