# Generated by Django 2.2.9 on 2020-02-22 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0016_auto_20200221_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
