# Generated by Django 2.2.9 on 2020-02-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0017_remove_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Is driver?'),
        ),
    ]
