# Generated by Django 2.2.9 on 2020-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0018_user_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(null=True, verbose_name='Student ID Number'),
        ),
    ]
